# title: no style, please! # name of the site
title: 宋一's blog !
# author: Riccardo Graziosi # name of site's author
author: Cyber-Song
# email: riccardo.graziosi97@gmail.com # email of site's author
email: Cyber-Song@163.com
url: https://riggraz.dev # root address of the site
# baseurl: "/no-style-please" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
# description: > # description of the site (multiple lines allowed)
#  A (nearly) no-CSS, fast, minimalist Jekyll theme.
description: > # description of the site (multiple lines allowed)
  \xe4\xba\xb2\xe7\x88\xb1\xe7\x9a\x84\xe9\x99\x8c\xe7\x94\x9f\xe4\xba\xba\xef\xbc\x8c\xe7\xa5\x9d\xe6\x82\xa8\xe6\x89\x80\xe6\xb1\x82\xe7\x9a\x86\xe6\x89\x80\xe6\x84\xbf\xef\xbc\x8c\xe6\x89\x80\xe8\xa1\x8c\xe5\x8c\x96\xe5\x9d\xa6\xe9\x80\x94\xef\xbc\x8c\xe5\xa4\x9a\xe5\x96\x9c\xe4\xb9\x90\xef\xbc\x8c\xe5\xb8\xb8\xe5\xae\x89\xe5\xae\x81\xef\xbc\x9b

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

# theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
